### ISSUE TITLE
Repeating Offline Inspections 😥

### ISSUE THREAD

**Issue by Usamaliaquat123** [5-StarDesigners/Equipment-Checker#1]
When i created an inspection in offline mode. The inspection has been created but when i connected to the internet and go to the previous inspections page. I saw the same inspection (that i was previously created in offline mode) seems two time's created .

**Resolving Options**
* May be endpoint trigger two times 
* May be the problem with an api 

**Need Suggestion's**

**Comment by syedatifgd** [comment]
This issue has been resolved in the latest commit with the commit id :  **b4bc748c093c079e837c414b3f3600877d37d035**
